vich_uploader:
    db_driver: orm

    mappings:
       pin_image:
           uri_prefix: /upda
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
